---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app jellyfin
  labels:
    # app.kubernetes.io/name: *app
    # app.kubernetes.io/instance: *app
    kubernetes.io/ingress.class: traefik
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "10G"
    nginx.ingress.kubernetes.io/client-max-buffer-size: "10G"
spec:
  ingressClassName: traefik-external
  rules:
    - host: &host jelly.icylair.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jelly-service
                port:
                  number: 8096
    - host: &host jelly.cloud.icylair.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jelly-service
                port:
                  number: 8096
    - host: &host jellyfin.icylair.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jelly-service
                port:
                  number: 8096
  tls:
  - hosts:
      - jellyfin.icylair.com
      - jelly.icylair.com
      - jelly.cloud.icylair.com
    secretName: icylair-com-all-prod
