---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-grafana-admin-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-cross-namespaces-secret
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials2
    template:
      engineVersion: v2
      data:
        admin_user: "{{ .admin_user }}"
        admin_password: "{{ .admin_password }}"
  dataFrom:
    - extract:
        key: observability/garfana/grafana-admin-credentials
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-grafana-ingress-crets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-cross-namespaces-secret
    kind: ClusterSecretStore
  target:
    name: grafana-ingress-crets
    template:
      engineVersion: v2
      data:
        admin_user: "{{ .admin_user }}"
        admin_password: "{{ .admin_password }}"
  dataFrom:
    - extract:
        key: observability/garfana/grafana-ingress-crets
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-grafana-oauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-cross-namespaces-secret
    kind: ClusterSecretStore
  target:
    name: grafana-oauth
    template:
      engineVersion: v2
      data:
        client_id: "{{ .client_id }}"
        client_secret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: observability/garfana/grafana-oauth
