---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - config_synapse.yaml
  - bridges.yaml
  - bridge_config.yaml
  - external-secrets.yaml
  # - secrets.yaml
  # - whatsapp-config.yaml
  # - whatsapp-service.yaml
# generatorOptions:
#   disableNameSuffixHash: true
# configMapGenerator:
#   - name: matrix-synapse2
#     files:
#       - homeserver.yaml=./config_synapse.yaml
#   - name: matrix-bridge-whatsapp-config2
#     files:
#       - config.yaml=./config_whatsapp.yaml
# configurations:
#   - kustomizeconfig.yaml
