apiVersion: v1
kind: Service
metadata:
  name: kube-api-vxlan
  labels:
    service-type: ingress-static
    service-type/vxlan: static
  annotations:
    lbipam.cilium.io/ips: 10.129.16.2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    component: kube-apiserver
    tier: control-plane
  ports:
    - port: 6443
