# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: external-secrets-alertmanager-secret
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: vault-backend-cross-namespaces-secret
#     kind: ClusterSecretStore
#   target:
#     name: alertmanager-secret
#     template:
#       engineVersion: v2
#       data:
#         alertmanager.yaml: |
#           route:
#             group_by: ['alertname', 'job']
#             group_wait: 30s
#             group_interval: 5m
#             repeat_interval: 3h
#             receiver: discord
#           receivers:
#           - name: discord
#             discord_configs:
#             - webhook_url: {{ .discord_webhook_token }}
#   dataFrom:
#     - extract:
#         key: observability/garfana/alertmanager-secret
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-ext-new
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-cross-namespaces-secret
    kind: ClusterSecretStore
  target:
    name: synapse-ext-new
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: matrix-synapse/postgres-synapse-user
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-pg-superuser
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-cross-namespaces-secret
    kind: ClusterSecretStore
  target:
    name: synapse-pg-superuser
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: matrix-synapse/postgres-synapse-superuser
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-synapse-pg-backup-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-cross-namespaces-secret
    kind: ClusterSecretStore
  target:
    name: minio-synapse-pg-backup-secrets
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_access_key }}"
  dataFrom:
    - extract:
        key: matrix-synapse/minio-s3-backup-secret
