---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace kube-system
resources:
  - release.yaml
  - ocirepository.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: values
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
