---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: synapse-databases
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn-system-base
    - name: external-secrets-vault-store
    - name: cloudnative-pg
  path: ./kubernetes/apps/apps/matrix-synapse/databases
  prune: true
  wait: true
  suspend: false
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  # healthChecks:
  #   - apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #     kind: HelmRelease
  #     name: cert-manager
  #     namespace: cert-manager
  interval: 15m
  retryInterval: 15m
  timeout: 10m
  targetNamespace: apps

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: synapse-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-base
    - name: synapse-databases
    - name: longhorn-system-base
    - name: synapse-databases
  path: ./kubernetes/apps/apps/matrix-synapse/  # gets the kustomisation so it can reach 2 files
  suspend: false
  wait: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  interval: 15m
  retryInterval: 15m
  timeout: 10m
  targetNamespace: apps
