apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - pg-synapse.yaml
  - pg-whatsapp.yaml
  - pg-meta.yaml
  # - secrets.yaml
  # - service.yaml
  # - external-secrets.yaml
